### ISSUE TITLE
Extension popup not appearing on click

### ISSUE THREAD

**Issue by Drutol** [gloaysa/no-otp#3]
Hello,

I'm having a little trouble with getting the popup from the extension button to display. After each browser restart I have to open the settings page and click save, after saving the popup will appear correctly every time. Tried both on Vivaldi and Edge, same behaviour. Thanks in advance!

My browser:
```
Vivaldi | 6.2.3105.51 (Stable channel) (64-bit)
Revision | 76144063ae8137b05a189fe91dfaf1ac12ce492d
OS | Windows 11 Version 22H2 (Build 22621.2283)
JavaScript | V8 11.6.189.20
```
Extension:
```
Version: 2.1
From Google Chrome Web Store
```

**Comment by gloaysa** [comment]
Hi Drutol, I can reproduce the issue on Chrome 117.0.5938.92 too.
I have dropped development for all my extensions for Chromium based browsers due to Google new policies regarding what extensions can do, nevertheless I will have a look at it, don't want to inconvenience my users :)

Edit: I can confirm it's also reproducible in Firefox v.885035
